name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]    
    steps:
      - name: Get the sources
        uses: actions/checkout@v1
      - name: scan for secrets
        id: scan-for-secrets
        uses: ./